Update readme with brief information about this repo
sclorg/sclorg-testing-farm pull request #12
Opened 2022-02-08 13:19 UTC by zmiklank

I was not really sure, what is the function of this repository, so I took a look and created a brief README.md.

However, I am not sure, if really all fmf plans here are used by the GitHub Actions, so please correct me, if this information is incorrect.

2022-02-08 14:56 UTC, phracek requested changes
Thanks for the PR!. Can you please rephrase it a bit more?

I would prefer also to mention in README.md also a list of plans.

2022-02-08 14:56 UTC, phracek commented on README.md
> +# Testing Farm FMF testing plans
I would prefer to mention here something like:

`FMF testing plans for using it in Testing Farm`.

2022-02-08 14:57 UTC, phracek commented
See the content of directory `https://github.com/sclorg/sclorg-testing-farm/tree/main/plans`. But it can be done as a separate pull request.

2022-02-09 15:02 UTC, zmiklank commented
@phracek, I have updated the PR as you wanted, thanks for the review.

However, I think, that the fedora.fmf should be updated, because it contains "centos7" strings. I thus didn't know what exactly should I write to the fedora column in the table.

Also, the description in the c9s fmf plan mentions only docker tests and not openshift tests, as is in, e.g., centos7 fmf plan. Is this correct?

2022-02-10 09:13 UTC, phracek approved these changes

2022-02-10 09:13 UTC, phracek commented on README.md
> +| `fedora.fmf`            | not sure, **TODO**        |
This will be used in the future for testing RHSCL containers on the Fedora host.

2022-02-10 09:15 UTC, phracek commented
> However, I think, that the fedora.fmf should be updated, because it contains "centos7" strings. I thus didn't know what exactly should I write to the fedora column in the table.
> 

This will be used later on. For now, we have not prepared infrastructure. As soon as we will use sclorg/testing-farm-as-github-action@v1, this will be used.
It is requested from @frenzymadness .

> Also, the description in the c9s fmf plan mentions only docker tests and not openshift tests, as is in, e.g., centos7 fmf plan. Is this correct?

For now, we are testing only container tests. Not openshift tests yet ;)

2022-02-11 07:30 UTC, zmiklank commented
Thank you for the explanations!

2022-02-11 07:30 UTC, merged